/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Latihan4GUI extends javax.swing.JFrame {

    /**
     * Creates new form Latihan4GUI
     */
    public Latihan4GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idnama = new javax.swing.JTextField();
        idabsen = new javax.swing.JTextField();
        buttonrpl = new javax.swing.JRadioButton();
        buttontkj = new javax.swing.JRadioButton();
        pgrm = new javax.swing.JCheckBox();
        dsnr = new javax.swing.JCheckBox();
        anmtr = new javax.swing.JCheckBox();
        basket = new javax.swing.JCheckBox();
        submit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        metu = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Biodata Siswa");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 20, 140, 50);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 100, 60, 50);

        jLabel3.setText("Absen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 150, 50, 30);

        jLabel4.setText("Jurusan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 190, 50, 30);

        jLabel5.setText("Hobi");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 230, 50, 30);
        getContentPane().add(idnama);
        idnama.setBounds(180, 110, 220, 30);
        getContentPane().add(idabsen);
        idabsen.setBounds(180, 150, 220, 30);

        buttonGroup1.add(buttonrpl);
        buttonrpl.setText("RPL");
        getContentPane().add(buttonrpl);
        buttonrpl.setBounds(180, 200, 70, 23);

        buttonGroup1.add(buttontkj);
        buttontkj.setText("TKJ");
        getContentPane().add(buttontkj);
        buttontkj.setBounds(310, 200, 43, 23);

        buttonGroup2.add(pgrm);
        pgrm.setText("PROGRAMING");
        getContentPane().add(pgrm);
        pgrm.setBounds(180, 240, 120, 23);

        buttonGroup2.add(dsnr);
        dsnr.setText("DESAINER");
        getContentPane().add(dsnr);
        dsnr.setBounds(310, 240, 160, 23);

        buttonGroup2.add(anmtr);
        anmtr.setText("ANIMATOR");
        anmtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anmtrActionPerformed(evt);
            }
        });
        getContentPane().add(anmtr);
        anmtr.setBounds(180, 280, 110, 23);

        buttonGroup2.add(basket);
        basket.setText("BASKET");
        getContentPane().add(basket);
        basket.setBounds(310, 280, 140, 23);

        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(79, 320, 100, 23);

        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(250, 320, 100, 23);

        metu.setText("EXIT");
        metu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metuActionPerformed(evt);
            }
        });
        getContentPane().add(metu);
        metu.setBounds(410, 320, 110, 23);

        jLabel6.setText("HASIL");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(280, 360, 90, 14);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\ts2.png")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 20, 280, 380);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 380, 440, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anmtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anmtrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anmtrActionPerformed

    private void metuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metuActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_metuActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String nama = idnama.getText();
        String absen = idabsen.getText();
        String jurusan;
        String hobi="";
        //untuk button
        if (buttonrpl.isSelected())
            jurusan = "RPL";
        else if (buttontkj.isSelected())
            jurusan = "TKJ";
        else
            jurusan = " ";
        // untuk hobi
        if (pgrm.isSelected())
            hobi+=pgrm.getText()+", ";
        if (anmtr.isSelected())
            hobi+=anmtr.getText()+", ";
        if (dsnr.isSelected())
            hobi+=dsnr.getText()+", ";
        if (basket.isSelected())
            hobi+=basket.getText()+", ";
        TA.setText("Nama Siswa : " +nama+"\nAbsen Siswa : " +absen+ "\nJurusan Anda : " +jurusan+ "\nHobi Anda : "+hobi);
      
    }//GEN-LAST:event_submitActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        TA.setText("");
        idnama.setText("");
        idabsen.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        pgrm.setSelected(false);
        anmtr.setSelected(false);
        dsnr.setSelected(false);
        basket.setSelected(false);
    }//GEN-LAST:event_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan4GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan4GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan4GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan4GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan4GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TA;
    private javax.swing.JCheckBox anmtr;
    private javax.swing.JCheckBox basket;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton buttonrpl;
    private javax.swing.JRadioButton buttontkj;
    private javax.swing.JCheckBox dsnr;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField idabsen;
    private javax.swing.JTextField idnama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton metu;
    private javax.swing.JCheckBox pgrm;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
